books/urls.py
from django.urls import path

from . import views

app_name = 'books'

urlpatterns = [
    path('', view=views.BookListView.as_view(), name='book_list'),
    path('new', view=views.BookCreateView.as_view(), name='book_new'),
    path('edit/<int:pk>', view=views.BookUpdateView.as_view(), name='book_edit'),
    path('delete/<int:pk>', view=views.BookDeleteView.as_view(), name='book_delete'),
    path('view/<int:pk>', view=views.BookView.as_view(), name='book_view')
]

project/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls', namespace='books'))
]

books/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    read = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('book_edit', kwargs={'pk': self.pk})

books/forms.py
from django import forms

from .models import Book


class BookForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {
            'class': 'form-control'
        }
        self.fields['author'].widget.attrs = {
            'class': 'form-control'
        }

    class Meta:
        model = Book
        fields = ('name', 'author', 'read')

books/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from . models import Book
from .forms import BookForm


class BookListView(generic.ListView):
    model = Book


class BookCreateView(generic.CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books:book_list')


class BookUpdateView(generic.UpdateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('books:book_list')


class BookDeleteView(generic.DeleteView):
    model = Book
    success_url = reverse_lazy('books:book_list')


class BookView(generic.DetailView):
    model = Book

books/templates/books/base.html
{% load static %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Książki</title>
  <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <style>
  body {
    background: whitesmoke;
  }
  #app {
    background: white;
    padding: 30px;
    margin: 30px auto;
    -webkit-box-shadow: 1px 1px 2px 0px rgba(224,224,224,1);
    -moz-box-shadow: 1px 1px 2px 0px rgba(224,224,224,1);
    box-shadow: 1px 1px 2px 0px rgba(224,224,224,1);
    border-radius: 4px;
  }
  </style>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/">Moje książki</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="btn btn-info btn-md" href="{% url "books:book_new" %}">+ Nowa książka</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container" id="app">
    {% block content %}{% endblock %}
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha256-3edrmyuQ0w65f8gfBsqowzjJe2iM6n0nKciPUp8y+7E="
  crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
  integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
  crossorigin="anonymous"></script>
</body>
</html>

books/templates/books/book_confirm_delete.html
{% extends 'books/base.html' %}

{% block content %}
<h1 class="my-4">Usuwnięcie -
  <small>{{ object }}</small>
</h1>
<div class="row">
  <div class="col-12">
    <form method="post">
      {% csrf_token %}
      <div class="alert alert-warning" role="alert">
        Czy jesteś pewny usunięcia {{ object }} ?
      </div>
      <input type="submit" class="btn btn-info" value="Tak, usuń tą książkę" />
      <a class="btn btn-success" href="{% url 'books:book_list' %}">Nie</a>
    </form>
  </div>
</div>
{% endblock %}

books/templates/books/book_detail.html
{% extends 'books/base.html' %}

{% block content %}
<h1 class="my-4">Detail -
  <small>{{ object.name }}</small>
</h1>
<div class="row">
  <div class="col-12">
    <ul class="list-group">
      <li class="list-group-item"><strong>Tytuł:</strong> {{ object.name }}</li>
      <li class="list-group-item"><strong>Autor:</strong> {{ object.author }}</li>
      <li class="list-group-item"><strong>Przeczytana:</strong> {%if object.read %}Tak{% else %}Nie{% endif %}</li>
    </ul>
  </div>
</div>
<div class="row mt-5">
  <div class="col-12">
    <a href="{% url 'books:book_list' %}" class="btn btn-info btn-sm">Powrót</a>
  </div>
</div>
{% endblock %}

books/templates/books/book_form.html
{% extends 'books/base.html' %}

{% block content %}
<h1 class="my-4">
  {% if not object.id %} Nowa Książka {% else %} Edycja - <small>{{ book.name }}</small>{% endif %}
</h1>
<div class="row">
  <div class="col-12">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" {% if not object.id %}value="Dodaj" {% else %} value="Zapisz" {% endif %} class="btn btn-success"/>
    </form>
  </div>
</div>
{% endblock %}

books/templates/books/book_list.html
{% extends 'books/base.html' %}

{% block content %}
<h1 class="my-4">
  <small>Lista książek</small>
</h1>
<div class="row">
  {% if object_list %}
  <div class="col-12">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Tytuł</th>
          <th scope="col">Autor</th>
          <th scope="col" class="text-center">Przeczytana?</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for book in object_list %}
        <tr>
          <td>{{ book.name }}</td>
          <td>{{ book.author }}</td>
          <td class="text-center">
            {% if book.read %}<span class="badge badge-info">Tak</span>{% else %}<span class="badge badge-danger">Nie</span>{% endif %}
          </td>
          <td class="text-right">
            <a href="{% url 'books:book_view' book.id %}"><button type="button" class="btn btn-sm btn-primary">Szczegóły</button></a>
            <a href="{% url 'books:book_edit' book.id %}"><button type="button" class="btn btn-sm btn-warning">Zmień</button></a>
            <a href="{% url 'books:book_delete' book.id %}"><button type="button" class="btn btn-sm btn-danger">Usuń</button></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <div class="col-12">
    <div class="alert alert-warning" role="alert">
      Lista książek jest pusta. Możesz <a class="badge badge-info" href="{% url "books:book_new" %}"><strong>dodać</strong></a> jedną.
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}